---
title: "netcdf in R"
author: "Fedor Baart"
date: "1 Mar 2016"
output: ioslides_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## When do we use netCDF
- data that fits in arrays
- variables need metadata (units, names)
- datasets needs metadata (title, author, lineage)



## How do I use netCDF in R

- <del>ncdf</del>
- ncdf4
- RNetCDF?

## NetCDF reading

```{r netcdf, echo = TRUE}
# install.packages("ncdf4")
library(ncdf4)
# OSX, Linux only
url <- "http://opendap.deltares.nl/thredds/dodsC/opendap/"
dataset <- "rijkswaterstaat/waterbase/sea_surface_height/id1-AMRGBNDN.nc"
nc <- nc_open(paste(url, dataset, sep=""))
nc
```

## NetCDF variables

```{r get var, echo=TRUE}
time <- ncvar_get(nc, 'time')
h <- ncvar_get(nc, 'sea_surface_height')
nc_close(nc)
```

## NetCDF variables

```{r plot, echo=TRUE}
library(ggplot2)
ggplot(data.frame(time=time, h=h), aes(x=time, y=h)) + geom_smooth()
```

## NetCDF with RNetCDF

```{r rnetcdf, echo=TRUE}
library(RNetCDF)
nc <- open.nc(paste(url, dataset, sep=""))
print.nc(nc)
```
## Get var with RNetCDF (not working for me)

```{r rnetcdf var, echo=TRUE}
print(try(var.get.nc(nc, 'time')))
close.nc(nc)
```


## NetCDF kickstarter

[zandmotor.citg.tudelft.nl/netcdfkickstarter](http://zandmotor.citg.tudelft.nl/netcdfkickstarter/)