---
title: "NetCDF rasters"
author: "Willem Stolte"
date: "January 14, 2016"
output: html_document
---

This an example script to read and plot netcdf rasters. The data are from the Deltares OPeNDAP server and are generated by IMARES (Lorna Teal) for the EU-VECTORS project.

```{r, message=F, warning=F, comment=F, results=F}
library(raster)
library(RNetCDF)

url_plaice <-"http://opendap.deltares.nl/thredds/fileServer/opendap/imares/plaice_large_2002/plaice_large_2002_day_98.nc" 

# download the netcdf file
download.file(url_plaice, "plaice.nc" , method = "auto",
              quiet = FALSE, mode="wb", cacheOK = TRUE)
con <- open.nc("plaice.nc")
var.inq.nc(con,0)$name
```

A simple plot using the default plot routine
```{r, message=F, warning=F, comment=F}

r <- raster("plaice.nc", varname = "Band1")
plot(r)
contour(r, add = TRUE)
```

A somewhat nicer plot is obtained using the ggplot package

```{r, message=F, warning=F, comment=F}
require(magrittr) #necessar for piping function
## function below is from https://github.com/dutri001/ggSpatial
## can alsoe be installed using
## devtools::install_github('dutri001/ggSpatial')
fortify.Raster <- function(x, maxPixel = 1000000) {
  
  if (ncell(x) > maxPixel) {
    x <- sampleRegular(x, maxPixel, asRaster=TRUE)
  }
  xy <- xyFromCell(x, seq_len(ncell(x)))
  out <- x %>%
    getValues() %>%
    data.frame(values = .) %>%
    cbind(xy)
  return(out)
}

require(ggplot2)
rf <- fortify.Raster(r)
p <- ggplot(rf, aes(x,y))
p + geom_raster(aes(fill = values)) +
  geom_contour() +
  scale_fill_gradient(low = "green", high = "red")
```

The raster can also be plotted using leaflet binding to generate a zoomable map:
```{r, message=F, warning=F, comment=F}
require(leaflet)
leaflet() %>%
  addTiles(group = "OSM (default)") %>%
  addRasterImage(r, colors = "Spectral", opacity = 0.6) 
```

